version: '3'

services:
  database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "9090:3306"
    volumes:
      - ../database/ecommerce:/var/lib/mysql
  test_database:
    image: 'mysql:8'
    environment:
      MYSQL_ROOT_PASSWORD: roottest
      MYSQL_DATABASE: ecommercetest
    ports:
      - "9070:3306"
    volumes:
      - ../database/ecommercetest:/var/lib/mysql
